//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserInterface.Commanding {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Commanding.ISimpleTwitterCommandService")]
    public interface ISimpleTwitterCommandService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleTwitterCommandService/Execute", ReplyAction="http://tempuri.org/ISimpleTwitterCommandService/ExecuteResponse")]
        void Execute(Commands.PostNewTweetCommand command);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleTwitterCommandService/Delete", ReplyAction="http://tempuri.org/ISimpleTwitterCommandService/DeleteResponse")]
        void Delete(Commands.DeleteTweetCommand command);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleTwitterCommandService/CreateNewChannel", ReplyAction="http://tempuri.org/ISimpleTwitterCommandService/CreateNewChannelResponse")]
        void CreateNewChannel(Commands.CreateNewChannelCommand command);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleTwitterCommandService/CreateUser", ReplyAction="http://tempuri.org/ISimpleTwitterCommandService/CreateUserResponse")]
        void CreateUser(Commands.CreateUserCommand command);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleTwitterCommandService/DeleteUser", ReplyAction="http://tempuri.org/ISimpleTwitterCommandService/DeleteUserResponse")]
        void DeleteUser(Commands.DeleteUserCommand command);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleTwitterCommandService/SetUserProperty", ReplyAction="http://tempuri.org/ISimpleTwitterCommandService/SetUserPropertyResponse")]
        void SetUserProperty(Commands.SetUserPropertyCommand command);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleTwitterCommandService/SetUserPassword", ReplyAction="http://tempuri.org/ISimpleTwitterCommandService/SetUserPasswordResponse")]
        void SetUserPassword(Commands.SetUserPasswordCommand command);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleTwitterCommandService/ValidateUser", ReplyAction="http://tempuri.org/ISimpleTwitterCommandService/ValidateUserResponse")]
        void ValidateUser(Commands.ValidateUserCommand command);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleTwitterCommandService/InvalidateUser", ReplyAction="http://tempuri.org/ISimpleTwitterCommandService/InvalidateUserResponse")]
        void InvalidateUser(Commands.InvalidateUserCommand command);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleTwitterCommandService/AddUserToRole", ReplyAction="http://tempuri.org/ISimpleTwitterCommandService/AddUserToRoleResponse")]
        void AddUserToRole(Commands.AddUserToRoleCommand command);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleTwitterCommandService/RemoveUserFromRole", ReplyAction="http://tempuri.org/ISimpleTwitterCommandService/RemoveUserFromRoleResponse")]
        void RemoveUserFromRole(Commands.RemoveUserFromRoleCommand command);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISimpleTwitterCommandServiceChannel : UserInterface.Commanding.ISimpleTwitterCommandService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SimpleTwitterCommandServiceClient : System.ServiceModel.ClientBase<UserInterface.Commanding.ISimpleTwitterCommandService>, UserInterface.Commanding.ISimpleTwitterCommandService {
        
        public SimpleTwitterCommandServiceClient() {
        }
        
        public SimpleTwitterCommandServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SimpleTwitterCommandServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimpleTwitterCommandServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimpleTwitterCommandServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Execute(Commands.PostNewTweetCommand command) {
            base.Channel.Execute(command);
        }
        
        public void Delete(Commands.DeleteTweetCommand command) {
            base.Channel.Delete(command);
        }
        
        public void CreateNewChannel(Commands.CreateNewChannelCommand command) {
            base.Channel.CreateNewChannel(command);
        }
        
        public void CreateUser(Commands.CreateUserCommand command) {
            base.Channel.CreateUser(command);
        }
        
        public void DeleteUser(Commands.DeleteUserCommand command) {
            base.Channel.DeleteUser(command);
        }
        
        public void SetUserProperty(Commands.SetUserPropertyCommand command) {
            base.Channel.SetUserProperty(command);
        }
        
        public void SetUserPassword(Commands.SetUserPasswordCommand command) {
            base.Channel.SetUserPassword(command);
        }
        
        public void ValidateUser(Commands.ValidateUserCommand command) {
            base.Channel.ValidateUser(command);
        }
        
        public void InvalidateUser(Commands.InvalidateUserCommand command) {
            base.Channel.InvalidateUser(command);
        }
        
        public void AddUserToRole(Commands.AddUserToRoleCommand command) {
            base.Channel.AddUserToRole(command);
        }
        
        public void RemoveUserFromRole(Commands.RemoveUserFromRoleCommand command) {
            base.Channel.RemoveUserFromRole(command);
        }
    }
}
