//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserInterface.ReadModelService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReadModelService.ISimpleTwitterReadModelService")]
    public interface ISimpleTwitterReadModelService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleTwitterReadModelService/GetTweets", ReplyAction="http://tempuri.org/ISimpleTwitterReadModelService/GetTweetsResponse")]
        ReadModel.TweetIndexItem[] GetTweets();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleTwitterReadModelService/GetChannels", ReplyAction="http://tempuri.org/ISimpleTwitterReadModelService/GetChannelsResponse")]
        ReadModel.ChannelIndexItem[] GetChannels();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleTwitterReadModelService/GetUsers", ReplyAction="http://tempuri.org/ISimpleTwitterReadModelService/GetUsersResponse")]
        ReadModel.UserIndexItem[] GetUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleTwitterReadModelService/UserValidated", ReplyAction="http://tempuri.org/ISimpleTwitterReadModelService/UserValidatedResponse")]
        bool UserValidated(System.Guid UserID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISimpleTwitterReadModelServiceChannel : UserInterface.ReadModelService.ISimpleTwitterReadModelService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SimpleTwitterReadModelServiceClient : System.ServiceModel.ClientBase<UserInterface.ReadModelService.ISimpleTwitterReadModelService>, UserInterface.ReadModelService.ISimpleTwitterReadModelService {
        
        public SimpleTwitterReadModelServiceClient() {
        }
        
        public SimpleTwitterReadModelServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SimpleTwitterReadModelServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimpleTwitterReadModelServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimpleTwitterReadModelServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ReadModel.TweetIndexItem[] GetTweets() {
            return base.Channel.GetTweets();
        }
        
        public ReadModel.ChannelIndexItem[] GetChannels() {
            return base.Channel.GetChannels();
        }
        
        public ReadModel.UserIndexItem[] GetUsers() {
            return base.Channel.GetUsers();
        }
        
        public bool UserValidated(System.Guid UserID) {
            return base.Channel.UserValidated(UserID);
        }
    }
}
